<?php

/**
 * Globally registers the 'dashicons' plugin
 *
 * This ensures plugin using it is on the latest version of Dashicons, and helps to avoid conflicts.
 */

/* !!!


IF YOU ARE EDITING THIS FILE, THEN YOU ARE EDITING A FILE THAT GETS OUTPUT FROM THE DASHICONS REPO!

https://github.com/WordPress/dashicons

DO NOT EDIT THIS FILE!

If you need to edit this file, edit index-header.php and index-footer.php in the Dashicons repo instead
OR if you're looking to change how SVGs get output, you'll need to edit strings in the Gruntfile :)

!!! */


function get_gridicon( $dashicon ) {
	$svg = "";

	switch ( $dashicon ) {
